include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false
