name: btl
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  algoliasearch: ^1.22.3
  authentication_repository:
   git: https://github.com/ISL270/authentication_repository
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.0
  dartx: ^1.2.0
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_inputs:
    git: https://github.com/ISL270/form_inputs
  formz: ^0.6.1
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  theme_tailor: ^3.0.1
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/core/assets_gen/
  line_length: 100


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/