name: btl
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  authentication_repository:
   git: https://github.com/ISL270/authentication_repository
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  form_inputs:
    git: https://github.com/ISL270/form_inputs
  formz: ^0.6.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  theme_tailor: ^3.0.1
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
