name: btl
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  theme_tailor: ^3.0.1
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
