// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlebltedAVf750lPlLkPNYGq5RsAFsPKg',
    appId: '1:1028269511628:web:a417dd2f239dfe521e0369',
    messagingSenderId: '1028269511628',
    projectId: 'btl-dev-69d91',
    authDomain: 'btl-dev-69d91.firebaseapp.com',
    storageBucket: 'btl-dev-69d91.appspot.com',
    measurementId: 'G-6B5L9V2JJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwdFGQq-sbUMcoj6k7H8h4TfJXmJlQlj4',
    appId: '1:1028269511628:android:7ac72f876ef421a81e0369',
    messagingSenderId: '1028269511628',
    projectId: 'btl-dev-69d91',
    storageBucket: 'btl-dev-69d91.appspot.com',
    authDomain: 'btl-dev-69d91.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN4Xop1QYz4zk0bQLe_nej_FXRZCOa86M',
    appId: '1:1028269511628:ios:bf78f0ad3cc550f21e0369',
    messagingSenderId: '1028269511628',
    projectId: 'btl-dev-69d91',
    storageBucket: 'btl-dev-69d91.appspot.com',
    iosBundleId: 'com.example.verygoodcore.btl.dev',
    authDomain: 'btl-dev-69d91.firebaseapp.com',
  );
}
